apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tmc-controllers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tmc-controllers
subjects:
- kind: ServiceAccount
  name: tmc-controllers
  namespace: default
