apiVersion: tenancy.kcp.io/v1alpha1
kind: WorkspaceType
metadata:
  name: universal
spec:
  initializer: true
  defaultAPIBindings:
  - path: root
    export: tenancy.kcp.io
  - path: root
    export: scheduling.kcp.io
  - path: root
    export: workload.kcp.io
  - path: root
    export: apiresource.kcp.io
  - path: root
    export: topology.kcp.io
  defaultChildren:
    types:
    - name: universal
      path: root
