apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  annotations:
    bootstrap.kcp.io/battery: root-compute-workspace
    extra.apis.kcp.io/compute.workload.kcp.io: "true"
  name: kubernetes
spec:
  latestResourceSchemas:
    - v124.ingresses.networking.k8s.io
    - v124.services.core
    - v124.deployments.apps
    - v124.pods.core
    - v124.endpoints.core
  maximalPermissionPolicy:
    local: {}
status: {}
