apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:tmc:authenticated:universal-workspacetype-use
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:tmc:universal-workspacetype-use
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
