name: build-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    runs-on: [ubuntu-latest]
    timeout-minutes: 8
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go
      - name: Check out code
        uses: actions/checkout@v2

      - name: ⚙️ Run build
        shell: bash
        run: |
          set -xe
          make all
          [[ -z "$(git status -s)" ]]
